spring:
  profiles:
    active: dev   # 기본 실행 환경 (local)
  application:
    name: mvp-be
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ktds.mvp.demo
  configuration:
    map-underscore-to-camel-case: true

# UptimeRobot 용
management:
  endpoints:
    web:
      exposure:
        include: health

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

rule-engine:
  url: http://localhost:3001