spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com/postgres?sslmode=require
    username: postgres.mnzfbmxhdzndowlajtwy
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info
    com:
      ktds:
        mvp:
          demo: debug

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger