spring:
  profiles:
    active: local   # 기본 실행 환경 (local)
  application:
    name: mvp-be
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ktds.mvp.demo
  configuration:
    map-underscore-to-camel-case: true